### PR TITLE
Mokabed dev np

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1106 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13)* status: 1 of 1106 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[readme.md, line 6 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13#-Lrn_vWl1T11fe1POkVc:-Lrn_vWl1T11fe1POkVd:b-yw9y1i) ([raw file](https://github.com/moka-guys/dnanexus_mokabed/blob/fcfe24fc7f39dd9da9a95ee9ae048b11f6d2d2bb/readme.md#L6)):*
> ```Markdown
> This app utilises the MokaBED code to generate BED files.
> 
> The app clones the production branch of the mokabed code (https://github.com/woook/mokabed)
> ```

it doesn't any more!
___
*[src/code.sh, line 29 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13#-LrnaOPX6gpleDvv_PAT:-LrnaOPX6gpleDvv_PAU:b-e1dn9k) ([raw file](https://github.com/moka-guys/dnanexus_mokabed/blob/fcfe24fc7f39dd9da9a95ee9ae048b11f6d2d2bb/src/code.sh#L29)):*
<details><summary><i alt="summary">Quoted 28 lines of code…</i></summary>

> ```
> #mv /home/dnanexus/in/transcript_file/$transcript_file_prefix.txt /home/dnanexus/$transcript_file_prefix.txt
> 
> #eval "$(ssh-agent -s)"
> #ssh-add ~/.ssh/id_rsa
> #git clone git@github.com:woook/mokabed.git
> 
> #cat /home/dnanexus/.ssh/id_rsa.pub | sudo tee -a /home/dnanexus/.ssh/authorized_keys
> #sudo cp ~/.ssh/* /root/.ssh/
> #chmod 600 /home/dnanexus/.ssh/id_rsa
> #ssh-keyscan -t rsa github.com 2>&1 >> /home/dnanexus/.ssh/known_hosts
> 
> #ssh -vT git@github.com
> 
> 
> #git clone git@github.com:woook/mokabed.git
> 
> # capture github API key
> #GITHUB_KEY=$(dx cat project-FQqXfYQ0Z0gqx7XG9Z2b4K43:mokabed_github_key)
> 
> #git clone https://$GITHUB_KEY@github.com/woook/mokabed.git
> 
> #cd mokabed
> 
> #git checkout production
> #ls
> 
> #bash ~/Anaconda2-4.2.0-Linux-x86_64.sh -b -p $HOME/Anaconda
> #export PATH="$HOME/Anaconda/bin:$PATH"
> ```
</details>

please remove rather than comment out (this goes for any other commented out code

**Review by aledj2 — COMMENTED** [review]
in future can name branches/PR's with the changes that are being  implemented please

> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13#-:-LrnaygF5ZbYrcX9I3qW:b-iz1hgp)* status: 1 of 1106 files reviewed, 2 unresolved discussions (waiting on @natashapinto)

**Review by natashapinto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13)* status: 1 of 1106 files reviewed, 2 unresolved discussions (waiting on @aledj2)

___
*[readme.md, line 6 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13#-Lrn_vWl1T11fe1POkVc:-LrnfXP-3iJTsQ8ikRMd:b-1ytl16) ([raw file](https://github.com/moka-guys/dnanexus_mokabed/blob/fcfe24fc7f39dd9da9a95ee9ae048b11f6d2d2bb/readme.md#L6)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

it doesn't any more!
</blockquote></details>

Yes! removed that...
___
*[src/code.sh, line 29 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13#-LrnaOPX6gpleDvv_PAT:-LrnfcU52CWYi2hAgGEq:b-896fix) ([raw file](https://github.com/moka-guys/dnanexus_mokabed/blob/fcfe24fc7f39dd9da9a95ee9ae048b11f6d2d2bb/src/code.sh#L29)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> #mv /home/dnanexus/in/transcript_file/$transcript_file_prefix.txt /home/dnanexus/$transcript_file_prefix.txt
> 
> #eval "$(ssh-agent -s)"
> #ssh-add ~/.ssh/id_rsa
> #git clone git@github.com:woook/mokabed.git
> 
> #cat /home/dnanexus/.ssh/id_rsa.pub | sudo tee -a /home/dnanexus/.ssh/authorized_keys
> #sudo cp ~/.ssh/* /root/.ssh/
> #chmod 600 /home/dnanexus/.ssh/id_rsa
> #ssh-keyscan -t rsa github.com 2>&1 >> /home/dnanexus/.ssh/known_hosts
> 
> #ssh -vT git@github.com
> 
> 
> #git clone git@github.com:woook/mokabed.git
> 
> # capture github API key
> #GITHUB_KEY=$(dx cat project-FQqXfYQ0Z0gqx7XG9Z2b4K43:mokabed_github_key)
> 
> #git clone https://$GITHUB_KEY@github.com/woook/mokabed.git
> 
> #cd mokabed
> 
> #git checkout production
> #ls
> 
> #bash ~/Anaconda2-4.2.0-Linux-x86_64.sh -b -p $HOME/Anaconda
> #export PATH="$HOME/Anaconda/bin:$PATH"
> ```
please remove rather than comment out (this goes for any other commented out code
</blockquote></details>

Done.

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13)* status: 2 of 1106 files reviewed, 2 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[readme.md, line 6 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13#-Lrn_vWl1T11fe1POkVc:-LrnxhD9DL1eEEYhgRIL:bo472g2) ([raw file](https://github.com/moka-guys/dnanexus_mokabed/blob/fcfe24fc7f39dd9da9a95ee9ae048b11f6d2d2bb/readme.md#L6)):*
<details><summary><i>Previously, natashapinto wrote…</i></summary><blockquote>

Yes! removed that...
</blockquote></details>

sorry, I should have been more specific, can you update it rather than remove it. Perhaps do a release of the mokabed code, and say this app uses version x  of the mokabed code (link to repo - maybe use the link after the repo has been moved).

**Review by aledj2 — APPROVED** [review]
I have reviewed the json, readme and src/code - all other changes are from the packaged up mokabed repo, which was code reviewed in that repo.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokabed/13#-:-Lro6Ao5CZIGZYoVMD0y:b-gazahz)* status: 3 of 1106 files reviewed, 1 unresolved discussion (waiting on @aledj2)

**Pull request merged**
